---
- name: TrainingWheelsProtocol - Red Team Low Hanging Fruit
  hosts: linux
  become: yes

  tasks:
    - name: Deploy Users
      include_tasks: users.yml

    - name: Install Tools
      include_tasks: tools.yml

    - name: deploy the MANgler
      include_tasks: MANgler.yml

    - name: create cron tasks
      include_tasks: cron.yml